Document: custom-motd
Title: Debian custom-motd Manual
Author: <insert document author here>
Abstract: This manual describes what custom-motd is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/custom-motd/custom-motd.sgml.gz

Format: postscript
Files: /usr/share/doc/custom-motd/custom-motd.ps.gz

Format: text
Files: /usr/share/doc/custom-motd/custom-motd.text.gz

Format: HTML
Index: /usr/share/doc/custom-motd/html/index.html
Files: /usr/share/doc/custom-motd/html/*.html
